#!/bin/sh

set -euo pipefail

[ -d /usr/src/app ] || {
  echo "This script is intended to be executed inside the docker container."
  exit 1
}

if [ -z "${CONTROL_REPO_PATH:-}" ]; then
  echo "Please set \${CONTROL_REPO_PATH} to the path within the container at which the control repository is mounted."
  exit 1
elif [ -d "${CONTROL_REPO_PATH:-}" ]; then
  chown -R presenter:presenter "${CONTROL_REPO_PATH}"
fi

exec /usr/bin/su presenter -c 'npm start'
